name: RICELab
description: RICELab Homepage
# paginate: 10
baseurl: '' # note: need to fix this in bib.html as well
plugins: [jekyll-paginate, jekyll-gist, jekyll/scholar]
encoding: utf-8
permalink: /blog/:year/:title/

scholar:
  style: assets/bibliography/tony-citation-style.csl
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  details_dir:    papers
  details_layout: paper-detail.html
  details_link:   '<!-- -->'

  query: "@*"

# Google Analytics
google_analytics: UA-19657956-2